# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "git-along-unstable-${version}";
  version = "2018-10-30";
  rev = "faed14fc82ef060ba0e3d095186c4d251c94bffe";

  goPackagePath = "github.com/nyarly/git-along";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/nyarly/git-along";
    sha256 = "1gk55vwwl5v3yb4v010a9y485qai8aqx446w18dbmycwi9zlryb0";
  };

  goDeps = ./deps.nix;

  meta = {
    description = "Manage project configuration and environment in side branches.";
    homepage = "https://github.com/nyarly/git-along";
  };
}
