# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
# With some hand-tuning (remove useless fetch* inputs)
{ stdenv, buildGoPackage, fetchgit }:

buildGoPackage rec {
  name = "git-along-unstable-${version}";
  version = "2019-04-18";
  rev = "365e61796cd75655af978062a14b2075d83a97e5";

  goPackagePath = "github.com/nyarly/git-along";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/nyarly/git-along";
    sha256 = "00aigic2d2rndmzgggb8343rc85jg8plmlhv1v27x9x2r7ck01ny";
  };

  goDeps = ./deps.nix;

  meta = {
    description = "Manage project configuration and environment in side branches.";
    homepage = "https://github.com/nyarly/git-along";
  };
}
